export const vendorcategories = [
  "Electronics",
  "Food & Beverages",
  "Technology & Software",
  "Logistics & Shipping",
  "Fashion & Apparel",
  "Printing & Packaging",
  "Software & Hardware",
  "Home Furniture",
  "Sustainable Packaging",
  "Marketing & Advertising",
];
export const purchaseOrderNumbers = [
  "PO-1001",
  "PO-1002",
  "PO-1003",
  "PO-1004",
  "PO-1005",
  "PO-1006",
  "PO-1007",
  "PO-1008",
  "PO-1009",
  "PO-1010",
];
export const paymentTerms = [
  "Net 30",
  "Net 45",
  "Net 60",
  "Due on Receipt",
  "COD (Cash on Delivery)",
  "Cash in Advance",
  "Partial Payment",
  "Installment",
  "30/60/90",
  "End of Month (EOM)",
  "Due in 15 days",
  "Upon Completion",
  "50% upfront, 50% on delivery",
];
export const invoiceNumbers = [
  "INV-00123",
  "INV-00124",
  "INV-00125",
  "INV-00126",
  "INV-00127",
  "INV-00128",
  "INV-00129",
  "INV-00130",
  "INV-00131",
  "INV-00132",
];
export const departments = [
  "Human Resources",
  "Finance",
  "Sales",
  "Marketing",
  "IT",
  "Customer Support",
  "Operations",
  "Product Development",
  "Legal",
  "R&D",
];
export const accounts = [
  "Admin Account",
  "Customer Account",
  "Supplier Account",
  "Partner Account",
  "Manager Account",
  "Employee Account",
  "Guest Account",
  "Premium User Account",
  "Free User Account",
  "Test Account",
];
export const locations = [
  "New York",
  "Los Angeles",
  "Chicago",
  "Houston",
  "Phoenix",
  "Philadelphia",
  "San Antonio",
  "San Diego",
  "Dallas",
  "San Jose",
  "Austin",
  "Jacksonville",
  "Fort Worth",
  "Columbus",
  "Indianapolis",
];
